title: Web Docs
description: Documentation, class notes, & project instructions for BWL's Pre-AP Computer Science: Web Development course.
theme: just-the-docs

url: https://webdocs.coderina.dev

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
